##
## Copyright (c) 2024 Marcos Bento
##
## Distributed under multiple licenses: Apache, MIT, Boost, Unlicense.
##
## See https://github.com/marcosbento/receptacles
##

FROM arm64v8/ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

# Generic

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
            software-properties-common \
            vim wget \
            build-essential \
            ninja-build \
            git git-lfs\
            doxygen \
            gpg-agent \
            pkg-config \
      && rm -rf /var/lib/apt/lists/*

# Development Tools

RUN apt-get update \
      && add-apt-repository ppa:ubuntu-toolchain-r/test \
      && apt-get install -y --no-install-recommends \
            gcc-9 g++-9 gcc-10 g++-10 gcc-11 g++-11 gcc-12 g++-12 gcc-13 g++-13 \
            clang-11 clang-12 clang-13 clang-14 clang-15 \
            clang-format clang-tidy clang-tools \
      && rm -rf /var/lib/apt/lists/*

RUN wget https://apt.llvm.org/llvm.sh \
      && chmod +x llvm.sh \
      && ./llvm.sh 16

RUN CMAKE_VERSION=3.28.1 \
        && CMAKE_ARCH=aarch64 \
        && cd /opt \
        && wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH}.tar.gz \
        && tar zxf cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH}.tar.gz \
        && ln -s cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH} cmake \
        && rm cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH}.tar.gz
ENV PATH="${PATH}:/opt/cmake/bin"

# Build Dependencies

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
            python3-dev \
            python3-venv \
            python3-pip \
      && rm -rf /var/lib/apt/lists/* \
      && pip3 install -U sphinx breathe sphinx_rtd_theme junit2html lxml Jinja2 

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
            libboost-all-dev \
            libfmt-dev \
            nlohmann-json3-dev \
            libgl1-mesa-dev qt6-base-dev libqt6core5compat6-dev libqt6svg6-dev libqt6charts6-dev libqt6opengl6-dev \
            libssl-dev \
            doxygen \
      && rm -rf /var/lib/apt/lists/*
